// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYTziMXt6IyAOHAlfwoMQjHUp1oQWwJhc',
    appId: '1:1024045374735:web:4414d6c11f6d125d79f27a',
    messagingSenderId: '1024045374735',
    projectId: 'kf-survey-fc78d',
    authDomain: 'kf-survey-fc78d.firebaseapp.com',
    storageBucket: 'kf-survey-fc78d.appspot.com',
    measurementId: 'G-54ZWLK10PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUgcshWnnzl4h-TPLVMb75pvMY7WBkJ6I',
    appId: '1:1024045374735:android:ac3060e401a66a7779f27a',
    messagingSenderId: '1024045374735',
    projectId: 'kf-survey-fc78d',
    storageBucket: 'kf-survey-fc78d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7KxxnLRT6M0KPpVAoUvOJHTGmOn8Rs5Q',
    appId: '1:1024045374735:ios:0f11d45ecd66c61779f27a',
    messagingSenderId: '1024045374735',
    projectId: 'kf-survey-fc78d',
    storageBucket: 'kf-survey-fc78d.appspot.com',
    iosClientId: '1024045374735-qtrufe7frarrdpqjrqacldjao8puq6l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kfSurvey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7KxxnLRT6M0KPpVAoUvOJHTGmOn8Rs5Q',
    appId: '1:1024045374735:ios:0f11d45ecd66c61779f27a',
    messagingSenderId: '1024045374735',
    projectId: 'kf-survey-fc78d',
    storageBucket: 'kf-survey-fc78d.appspot.com',
    iosClientId: '1024045374735-qtrufe7frarrdpqjrqacldjao8puq6l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kfSurvey',
  );
}
