// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoDev75VaFC3V0S1PkwnDuv1Snp57LsEg',
    appId: '1:667429940688:web:4113c9a22979cb0a3c5dd5',
    messagingSenderId: '667429940688',
    projectId: 'kf-survey',
    authDomain: 'kf-survey.firebaseapp.com',
    databaseURL: 'https://kf-survey.firebaseio.com',
    storageBucket: 'kf-survey.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9F4ygH2pl77Y10HODxIXnJDrzUKRZcwc',
    appId: '1:667429940688:android:c0a3173554bba77b3c5dd5',
    messagingSenderId: '667429940688',
    projectId: 'kf-survey',
    databaseURL: 'https://kf-survey.firebaseio.com',
    storageBucket: 'kf-survey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAIyDOB1dLrZyjeUEwj5FUQr3LoTx2PZg',
    appId: '1:667429940688:ios:322eda3849dac5263c5dd5',
    messagingSenderId: '667429940688',
    projectId: 'kf-survey',
    databaseURL: 'https://kf-survey.firebaseio.com',
    storageBucket: 'kf-survey.appspot.com',
    iosClientId: '667429940688-5lpnfvjo5cjmef66ffiovtqjj6s0gov9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kfSurvey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAIyDOB1dLrZyjeUEwj5FUQr3LoTx2PZg',
    appId: '1:667429940688:ios:322eda3849dac5263c5dd5',
    messagingSenderId: '667429940688',
    projectId: 'kf-survey',
    databaseURL: 'https://kf-survey.firebaseio.com',
    storageBucket: 'kf-survey.appspot.com',
    iosClientId: '667429940688-5lpnfvjo5cjmef66ffiovtqjj6s0gov9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kfSurvey',
  );
}
